# Generated by Django 5.2.7 on 2026-01-10 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0002_alter_club_logo'),
    ]

    operations = [
        migrations.AddField(
            model_name='clubmembership',
            name='executive_photo',
            field=models.ImageField(blank=True, null=True, upload_to='club_executives/'),
        ),
        migrations.AddField(
            model_name='clubmembership',
            name='executive_title',
            field=models.CharField(blank=True, help_text="Optional title like 'Head of Operations'", max_length=100),
        ),
    ]
